/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FlowStatePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/FlowStateView.ts
var import_obsidian = require("obsidian");

// src/types.ts
var SECTIONS = [
  { key: "in_progress", label: "In Progress" },
  { key: "overdue", label: "Overdue" },
  { key: "today", label: "Today" },
  { key: "inbox", label: "Inbox", limit: 14 }
];

// src/FlowStateView.ts
var VIEW_TYPE = "flowstate-tasks-view";
var FlowStateView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.refreshTimer = null;
    this.collapsedSections = {};
    this.containerEl_content = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "FlowState";
  }
  getIcon() {
    return "check-circle";
  }
  async onOpen() {
    this.loadCollapsedState();
    this.render();
    this.startAutoRefresh();
  }
  async onClose() {
    this.stopAutoRefresh();
  }
  startAutoRefresh() {
    this.stopAutoRefresh();
    const interval = this.plugin.settings.refreshInterval * 1e3;
    if (interval > 0) {
      this.refreshTimer = window.setInterval(() => {
        this.refreshData();
      }, interval);
      this.registerInterval(this.refreshTimer);
    }
  }
  stopAutoRefresh() {
    if (this.refreshTimer !== null) {
      window.clearInterval(this.refreshTimer);
      this.refreshTimer = null;
    }
  }
  loadCollapsedState() {
    try {
      const saved = localStorage.getItem("flowstate-collapsed");
      if (saved) {
        this.collapsedSections = JSON.parse(saved);
      }
    } catch (e) {
      this.collapsedSections = {};
    }
  }
  saveCollapsedState() {
    localStorage.setItem("flowstate-collapsed", JSON.stringify(this.collapsedSections));
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("flowstate-container");
    if (!this.plugin.settings.apiKey) {
      this.renderSetupPrompt(container);
      return;
    }
    this.renderHeader(container);
    this.containerEl_content = container.createDiv({ cls: "flowstate-content" });
    this.renderLoading(this.containerEl_content);
    this.refreshData();
  }
  renderSetupPrompt(container) {
    const prompt = container.createDiv({ cls: "flowstate-setup" });
    prompt.createEl("h3", { text: "Welcome to FlowState" });
    prompt.createEl("p", {
      text: "Configure your API URL and key in settings to get started.",
      cls: "flowstate-setup-text"
    });
    const btn = prompt.createEl("button", {
      text: "Open Settings",
      cls: "mod-cta"
    });
    btn.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById("flowstate-tasks");
    });
  }
  renderHeader(container) {
    const header = container.createDiv({ cls: "flowstate-header" });
    const addRow = header.createDiv({ cls: "flowstate-add-row" });
    const input = addRow.createEl("input", {
      type: "text",
      placeholder: "Add a task\u2026",
      cls: "flowstate-add-input"
    });
    const addBtn = addRow.createEl("button", {
      text: "Add",
      cls: "flowstate-add-btn"
    });
    const submitTask = async () => {
      const text = input.value.trim();
      if (!text)
        return;
      try {
        await this.plugin.api.createTask(text);
        input.value = "";
        new import_obsidian.Notice("Task added");
        this.refreshData();
      } catch (e) {
        new import_obsidian.Notice("Failed to add task");
      }
    };
    addBtn.addEventListener("click", submitTask);
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        submitTask();
    });
    const actions = header.createDiv({ cls: "flowstate-actions" });
    const refreshBtn = actions.createEl("button", {
      cls: "flowstate-icon-btn clickable-icon",
      attr: { "aria-label": "Refresh" }
    });
    (0, import_obsidian.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.addEventListener("click", () => this.refreshData());
    const openBtn = actions.createEl("button", {
      cls: "flowstate-icon-btn clickable-icon",
      attr: { "aria-label": "Open FlowState in browser" }
    });
    (0, import_obsidian.setIcon)(openBtn, "external-link");
    openBtn.addEventListener("click", () => {
      window.open(this.plugin.settings.apiUrl, "_blank");
    });
  }
  async refreshData() {
    if (!this.containerEl_content)
      return;
    try {
      const data = await this.plugin.api.getContext();
      this.containerEl_content.empty();
      let hasAnyTasks = false;
      for (const section of SECTIONS) {
        const tasks = data[section.key];
        if (tasks.length > 0)
          hasAnyTasks = true;
        this.renderSection(this.containerEl_content, section.key, section.label, tasks, section.limit);
      }
      if (!hasAnyTasks) {
        this.containerEl_content.createDiv({
          cls: "flowstate-empty",
          text: "No tasks \u2014 you're all clear!"
        });
      }
    } catch (e) {
      this.containerEl_content.empty();
      this.renderError(this.containerEl_content, e);
    }
  }
  renderLoading(container) {
    container.createDiv({ cls: "flowstate-loading", text: "Loading tasks\u2026" });
  }
  renderError(container, error) {
    const el = container.createDiv({ cls: "flowstate-error" });
    const msg = error instanceof Error ? error.message : "Connection failed";
    el.createEl("p", { text: `Error: ${msg}` });
    const retryBtn = el.createEl("button", { text: "Retry", cls: "mod-cta" });
    retryBtn.addEventListener("click", () => this.refreshData());
  }
  renderSection(container, key, label, tasks, limit) {
    var _a;
    if (tasks.length === 0)
      return;
    const section = container.createDiv({ cls: "flowstate-section" });
    const isCollapsed = (_a = this.collapsedSections[key]) != null ? _a : false;
    const headerEl = section.createDiv({ cls: "flowstate-section-header" });
    const chevron = headerEl.createSpan({ cls: "flowstate-chevron" });
    (0, import_obsidian.setIcon)(chevron, isCollapsed ? "chevron-right" : "chevron-down");
    const totalCount = tasks.length;
    const displayLimit = limit && limit < totalCount ? limit : void 0;
    const countText = displayLimit ? `${displayLimit} of ${totalCount}` : `${totalCount}`;
    headerEl.createSpan({
      text: `${label.toUpperCase()} (${countText})`,
      cls: "flowstate-section-title"
    });
    headerEl.addEventListener("click", () => {
      this.collapsedSections[key] = !this.collapsedSections[key];
      this.saveCollapsedState();
      this.refreshData();
    });
    if (!isCollapsed) {
      const list = section.createDiv({ cls: "flowstate-task-list" });
      const visibleTasks = displayLimit ? tasks.slice(0, displayLimit) : tasks;
      for (const task of visibleTasks) {
        this.renderTask(list, task);
      }
    }
  }
  renderTask(container, task) {
    const row = container.createDiv({ cls: "flowstate-task" });
    const checkbox = row.createEl("input", {
      type: "checkbox",
      cls: "task-list-item-checkbox flowstate-checkbox"
    });
    checkbox.addEventListener("click", async (e) => {
      e.preventDefault();
      row.addClass("flowstate-task-completing");
      try {
        await this.plugin.api.completeTask(task.id);
        row.remove();
        new import_obsidian.Notice("Task completed");
        this.refreshData();
      } catch (e2) {
        row.removeClass("flowstate-task-completing");
        new import_obsidian.Notice("Failed to complete task");
      }
    });
    const body = row.createDiv({ cls: "flowstate-task-body" });
    const textLine = body.createDiv({ cls: "flowstate-task-text" });
    textLine.createSpan({ text: task.text });
    if (task.is_important) {
      textLine.createSpan({ text: " \u2B50", cls: "flowstate-important" });
    }
    const meta = body.createDiv({ cls: "flowstate-task-meta" });
    if (task.category) {
      meta.createSpan({
        text: task.category,
        cls: "flowstate-category"
      });
    }
    if (task.priority >= 3) {
      const priorityLabel = task.priority === 4 ? "Urgent" : "High";
      meta.createSpan({
        text: priorityLabel,
        cls: `flowstate-priority flowstate-priority-${task.priority}`
      });
    }
    if (task.energy_level) {
      const icons = {
        low: "\u{1F50B}",
        medium: "\u26A1",
        high: "\u{1F525}"
      };
      const icon = icons[task.energy_level] || "";
      if (icon) {
        meta.createSpan({ text: icon, cls: "flowstate-energy" });
      }
    }
    if (task.deadline) {
      const deadlineDate = new Date(task.deadline);
      const now = /* @__PURE__ */ new Date();
      now.setHours(0, 0, 0, 0);
      const isOverdue = deadlineDate < now;
      const formatted = deadlineDate.toLocaleDateString(void 0, {
        month: "short",
        day: "numeric"
      });
      meta.createSpan({
        text: `${isOverdue ? "\u26A0\uFE0F " : ""}Due ${formatted}`,
        cls: `flowstate-deadline ${isOverdue ? "flowstate-overdue" : ""}`
      });
    }
  }
};

// src/FlowStateApi.ts
var import_obsidian2 = require("obsidian");
var FlowStateApi = class {
  constructor(settings) {
    this.settings = settings;
  }
  get headers() {
    return {
      "X-API-Key": this.settings.apiKey,
      "Content-Type": "application/json"
    };
  }
  url(path) {
    return `${this.settings.apiUrl.replace(/\/+$/, "")}${path}`;
  }
  async getContext() {
    const response = await (0, import_obsidian2.requestUrl)({
      url: this.url("/agent/context"),
      headers: this.headers
    });
    return response.json;
  }
  async createTask(text) {
    await (0, import_obsidian2.requestUrl)({
      url: this.url("/tasks"),
      method: "POST",
      headers: this.headers,
      body: JSON.stringify({ text })
    });
  }
  async completeTask(id) {
    await (0, import_obsidian2.requestUrl)({
      url: this.url(`/tasks/${id}/complete`),
      method: "PATCH",
      headers: this.headers
    });
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  apiUrl: "http://localhost:8000",
  apiKey: "",
  refreshInterval: 60
};

// src/main.ts
var FlowStatePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.api = new FlowStateApi(this.settings);
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE, (leaf) => new FlowStateView(leaf, this));
    this.addRibbonIcon("check-circle", "Open FlowState", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-flowstate-panel",
      name: "Open FlowState panel",
      callback: () => this.activateView()
    });
    this.addSettingTab(new FlowStateSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.api = new FlowStateApi(this.settings);
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.api = new FlowStateApi(this.settings);
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
  }
};
var FlowStateSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("FlowState API URL").setDesc("Base URL of your FlowState server").addText(
      (text) => text.setPlaceholder("http://localhost:8000").setValue(this.plugin.settings.apiUrl).onChange(async (value) => {
        this.plugin.settings.apiUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("API Key").setDesc("Your FlowState API key").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("Enter API key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Auto-refresh interval").setDesc("Seconds between automatic refreshes (0 to disable)").addText(
      (text) => text.setPlaceholder("60").setValue(String(this.plugin.settings.refreshInterval)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.refreshInterval = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Test connection").setDesc("Verify your API settings are correct").addButton(
      (btn) => btn.setButtonText("Test").onClick(async () => {
        try {
          const data = await this.plugin.api.getContext();
          const total = data.in_progress.length + data.overdue.length + data.today.length + data.inbox.length;
          new import_obsidian3.Notice(`Connected! ${total} tasks found.`);
        } catch (e) {
          const msg = e instanceof Error ? e.message : "Unknown error";
          new import_obsidian3.Notice(`Connection failed: ${msg}`);
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Open FlowState Web UI").setDesc("Open the full web interface in your browser").addButton(
      (btn) => btn.setButtonText("Open").onClick(() => {
        window.open(this.plugin.settings.apiUrl, "_blank");
      })
    );
  }
};
